# Generated by Django 5.0.2 on 2024-03-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holistskin_app', '0003_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('usn', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('college_name', models.CharField(max_length=100)),
                ('offers_status', models.CharField(max_length=60)),
                ('start_date', models.CharField(max_length=60)),
                ('end_date', models.CharField(max_length=60)),
                ('proj_report', models.CharField(max_length=60)),
                ('timeStamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='timestamp',
            new_name='timeStamp',
        ),
    ]
